# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classification_large',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Classification_middle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('largeClassId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contributions.Classification_large')),
            ],
        ),
        migrations.CreateModel(
            name='Classification_small',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('middleClassId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contributions.Classification_middle')),
            ],
        ),
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('alert', models.BooleanField(default=False)),
                ('smallClassId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contributions.Classification_small')),
            ],
        ),
    ]
