# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 17:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
        ('Contributions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('pay', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('expense', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('image', models.ImageField(upload_to='images/')),
                ('deadLine', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('url', models.URLField(blank=True)),
                ('isConfirm', models.BooleanField(default=False)),
                ('createUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.BasicInfo')),
            ],
        ),
        migrations.CreateModel(
            name='replyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=2000)),
                ('createUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.BasicInfo')),
                ('orderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contributions.orderInfo')),
            ],
        ),
        migrations.RemoveField(
            model_name='items',
            name='smallClassId',
        ),
        migrations.AddField(
            model_name='classification_small',
            name='alert',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='items',
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='smallClassId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contributions.Classification_small'),
        ),
    ]
